build:
  command: next build
  commandOrigin: ui
  environment:
    - NEXT_PRIVATE_TARGET
  publish: /opt/build/repo/.next
  publishOrigin: config
plugins:
  - inputs: {}
    origin: config
    package: '@netlify/plugin-nextjs'